name: "Terraform CI"


on:
  push:
    branches: [main, feature-infra]
  pull_request:
    branches: [main]


jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rg

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Init and Run TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Init and Run TFLint
        run: |
          tflint --init || true
          tflint --init || true
          tflint -f compact

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate